resources:
  - name: github_kashyaprahul94_repo
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      gitProvider: github_kashyaprahul94
      branches:
        include: ^{{gitBranch}}$
      files:
        include: (.*\.(env|yml|md))$
        exclude: prod.env
        
pipelines:
  - name: FooPipeline_gh
    steps:
      - name: FooPipeline_gh_step
        type: Bash
        configuration:
          inputResources:
            - name: github_kashyaprahul94_repo
        execution:
          onExecute:
          	- printenv
