pipelines:
  - name: pipelines_hello
    steps:
    - name: step_1
      type: Bash
      execution:
        onExecute:
          - add_run_variables var1="foo"
          - add_run_variables var2="bar"
        onComplete:
          - echo "${step_name} Completed"

    - name: step_2
      type: Bash
      configuration:
        inputSteps:
          - name: step_1
      execution:
        onExecute:
          - add_run_variables var3="baz"
          - add_run_variables var1="foofoofoo"
        onComplete:
          - echo "${step_name} Completed"

    - name: step_3
      type: Bash
      configuration:
        inputSteps:
          - name: step_2
      execution:
        onExecute:
          - echo "var1 - ${var1}"
          - echo "var2 - ${var2}"
          - echo "var3 - ${var3}"
        onComplete:
          - echo "${step_name} Completed"
