pipelines:
  - name: pipelines_hello
    steps:

      - name: step_1
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - foo_val: foo
              bar_val: bar
            - foo_val: foofoo
              bar_val: barbar
        execution:
          onStart:
            - mkdir -p files
            - filename="${foo_val}_${bar_val}.txt"
            - echo "foo_bar" > ./files/$filename
          onExecute:
            - add_run_files ./files state
            - set_step_var "foo" ${foo_val}
            - set_step_var "bar" ${bar_val}

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onStart:
            - restore_run_files state ./files
          onExecute:
            - cat ./files/foo_bar.txt
            - cat ./files/foofoo_barbar.txt
            - get_step_var "step_1" "foo"
            - get_step_var "step_1" "bar"
