
resources:
  - name: source_repo
    type: GitRepo
    configuration:
      gitProvider: kashyaprahul94_github
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: master
 
pipelines:     
    - name: pipelines_hello
      configuration:
        environmentVariables:
          readOnly:
            my_env_var: "hello"
      steps:
        - name: step_1
          type: Bash
#           configuration:
#             inputResources:
#               - name: source_repo
          execution:
            onExecute:
              - echo $my_env_var
