pipelines:
  - name: pipelines_hello
    steps:
    - name: step_1
      type: Bash
      execution:
        onExecute:
          - add_run_variables foo="bar"
          - add_run_variables stepId=${step_id}
          - add_run_variables stepletId=${steplet_id}
        onComplete:
          - echo "${step_name} Completed"

    - name: step_2
      type: Bash
      configuration:
        inputSteps:
          - name: step_1
      execution:
        onExecute:
          - printenv
          - echo "foo - ${foo}"
          - echo "last step id - ${step_id}"
          - echo "last steplet id - ${steplet_id}"
          - echo "current step id - ${stepId}"
          - echo "current steplet id - ${stepletId}"
        onComplete:
          - echo "${step_name} Completed"
