pipelines:     
  - name: pipelines_hello
    steps:  

      - name: step_1
        type: Bash
        execution:
          onExecute:
            - echo "Start..."

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onStart:
            - mkdir -p files
            - filename="${step_name}_${steplet_number}"
            - echo "I was on step name - ${step_name} step id - ${step_name} steplet number - ${steplet_number} steplet id - ${steplet_id}" > ./files/$filename
          onExecute:
            - add_run_files ./files state
            - add_run_variables step2_step_id=${step_id}
            - add_run_variables step2_steplet_id=${steplet_id}
          onComplete:
            - echo "${step_name} Completed"

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onStart:
            - mkdir -p files
            - filename="${step_name}_${steplet_number}"
            - echo "I was on step name - ${step_name} step id - ${step_name} steplet number - ${steplet_number} steplet id - ${steplet_id}" > ./files/$filename
          onExecute:
            - add_run_files ./files state
            - add_run_variables step3_step_id=${step_id}
            - add_run_variables step3_steplet_id=${steplet_id}
          onComplete:
            - echo "${step_name} Completed"

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
            - name: step_3
        execution:
          onStart:
            - restore_run_files state ./files
          onExecute:
            - echo "state file contents - "
            - cat ./files/*
            - echo "step2_step_id --> ${step2_step_id}"
            - echo "step2_steplet_id --> ${step2_steplet_id}"
            - echo "step3_step_id --> ${step3_step_id}"
            - echo "step3_steplet_id --> ${step3_steplet_id}"
          onComplete:
            - echo "${step_name} Completed"
