pipelines:
  - name: pipelines_hello
    steps:

      - name: step_1
        type: PreMatrix
        execution:
          onStart:
            - mkdir -p files
            - filename="foo.txt"
            - echo "Hey coming from pre matrix" > ./files/$filename
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"

      - name: step_2
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - foo_val: foo
              bar_val: bar
              env_val: linux
            - foo_val: foofoo
              bar_val: barbar
              env_val: mac
        execution:
          onStart:
            - ls -al
            - cat ./files/*
            - mkdir -p files
            - filename="${step_name}_${steplet_number}"
            - echo "I was on step name - ${step_name} step id - ${step_id} steplet number - ${steplet_number} steplet id - ${steplet_id}" > ./files/$filename
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - add_run_variables "foo_step_1_steplet_${steplet_number}=${foo_val}"
            - add_run_variables "bar_step_1_steplet_${steplet_number}=${bar_val}"

      - name: step_3
        type: PostMatrix
        execution:
          onStart:
            - ls -al
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
