
resources:
  - name: source_repo
    type: GitRepo
    configuration:
      gitProvider: kashyaprahul94_github
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: master
 
pipelines:     
    - name: pipelines_hello
      steps:
        - name: step_1
          type: Bash
          execution:
            onExecute:
              - printenv
