pipelines:
  - name: First_Pipeline_Long_Pipeline_Name_Long
    steps:
      - name: First_Step
        type: Bash
        configuration:
          integrations:
            - name: simple_mail
        execution: 
          onExecute:
            - echo "Step 1"
            - send_notification simple_mail --recipients 'khazinawaz@gmail.com'
            
      - name: Second_Step
        type: Bash
        configuration:
          inputSteps:
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
            
      - name: Third_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Second_Step
        execution: 
          onExecute:
            - echo "Step 2"
          
      - name: Fourth_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Third_Step
        execution: 
          onExecute:
            - echo "Step 2"
            
