resources:
  - name: test_git_repo
    type: GitRepo
    configuration:
      gitProvider: github_kashyaprahul94
      path: kashyaprahul94/test-jfrog-pipelines

pipelines:
  - name: pipeline_S_Bash_Util_0003_rahulk
    steps:
      - name: S_Bash_Util_0003_rahulk
        type: Bash
        configuration:
          inputResources:
            - name: test_git_repo

        execution:
          onExecute:
            - echo "image resource path is $res_myImage_resourcePath"
            - add_pipeline_variables pipelineVariable="asdffdjksfj.       k455457457"

      - name: S_Bash_Util_0003_2_rahulk
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: repo_pipe
          inputSteps:
            - name:  S_Bash_Util_0003_rahulk

        execution:
          onExecute:
            - $pipelineVariable
