
resources:
  - name: source_repo
    type: GitRepo
    configuration:
      gitProvider: kashyaprahul94_github
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: master
 
pipelines:     
    - name: pipelines_hello
      steps:
#         - name: step_1
#           type: Bash
#           configuration:
#             inputResources:
#               - name: source_repo
#           execution:
#             onExecute:
#               - printenv
        - name: matrix_example
          type: Matrix
          stepMode: Bash
          stepletMultipliers:
            environmentVariables:
              - animal:    dog
                mineral:   copper
                vegetable: carrot
#               - animal:    goat
#                 mineral:   iron
#                 vegetable: broccoli
#               - animal:    lizard
#                 mineral:   lead
          execution:
            onExecute:
              - echo "Executing matrix step on ${steplet_id}"
              - echo "Variation animal = ${animal}, mineral = ${mineral}, vegetable = ${vegetable}"
              - printenv
