pipelines:
  - name: pipelines_hello
    steps:

      - name: step_1
        type: Bash
        execution:
          onExecute:
            - add_run_variables var1="foo"
            - add_run_variables var2="bar"

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - add_run_variables var3="baz"
            - add_run_variables var1="foofoofoo"

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo "var1 - ${var1}"
            - echo "var2 - ${var2}"
            - echo "var3 - ${var3}"
            - if [ "$var1" != "foofoofoo" ]; then exit 1; fi
            - if [ "$var1" != "bar" ]; then exit 1; fi
            - if [ "$var1" != "baz" ]; then exit 1; fi
