resources:
  - name: fooGit
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      gitProvider: github_kashyaprahul94
      branches:
        include: ^{{gitBranch}}$
      files:
        include: (.*\.(env|yml))$
        exclude: prod.env
        
pipelines:
  - name: FooPipeline
    steps:
      - name: FooPipelineStep
        type: Bash
        configuration:
          inputResources:
            - name: fooGit
        execution: 
          onExecute:
            - printenv
