resources:
  - name: github_kashyaprahul94_repo
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      gitProvider: github_kashyaprahul94
      buildOn:
        commit: false
        pullRequestCreate: true
        pullRequestClose: false
        
pipelines:
  - name: test_env_vars_gh
    steps:
      - name: first_step
        type: Bash
        configuration:
          inputResources:
            - name: github_kashyaprahul94_repo
              trigger: true
        execution:
          onExecute:
            - base_branch=$(find_resource_variable "github_kashyaprahul94_repo" "baseCommitRef")
            - head_branch=$(find_resource_variable "github_kashyaprahul94_repo" "headCommitRef")
            - echo "base_branch - ${base_branch}"
            - echo "head_branch - ${head_branch}"
            - if [ "$head_branch" == "pr_env_var" ]; then exit 1; fi
