pipelines:     
  - name: pipelines_hello
    steps:

      - name: step__1
        type: Bash
        execution:
          onExecute:
            - echo "Hello from the step 1"

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step__1
          affinityGroup: ag_foo
          priority: 4
        execution:
          onExecute:
            - echo "Hello from the step 2"

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step__1
          affinityGroup: ag_foo
          priority: 1
        execution:
          onExecute:
            - echo "Hello from the step 3"

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step__1
          affinityGroup: ag_foo
          priority: 3
        execution:
          onExecute:
            - echo "Hello from the step 4"

      - name: step_5
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
            - name: step_3
            - name: step_4
          affinityGroup: ag_foo
          priority: 4
        execution:
          onExecute:
            - echo "Hello from the step 5"

      - name: step_6
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
            - name: step_3
            - name: step_4
          affinityGroup: ag_foo
          priority: 2
        execution:
          onExecute:
            - echo "Hello from the step 6"

      - name: step_7
        type: Bash
        configuration:
          inputSteps:
            - name: step_5
            - name: step_6
          affinityGroup: ag_foo
          priority: 2
        execution:
          onExecute:
            - echo "Hello from the step 7"
