pipelines:     
  - name: pipelines_hello
    steps:

      - name: step_1
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          environmentVariables:
            - foo_val: foo
              bar_val: bar
            - foo_val: foofoo
              bar_val: barbar
        execution:
          onStart:
            - mkdir -p files
            - filename="${step_name}_${steplet_number}"
            - echo "I was on step name - ${step_name} step id - ${step_name} steplet number - ${steplet_number} steplet id - ${steplet_id}" > ./files/$filename
          onExecute:
            - echo "Executing matrix step on ${steplet_id}"
            - add_run_files ./files state
            - add_run_variables foo_step_1_steplet_{steplet_number}=${foo_val}
            - add_run_variables bar_step_1_steplet_{steplet_number}=${bar_val}
          onComplete:
            - echo "Steplet #${steplet_number} Completed"
            
      - name: step_2
        type: Bash
        execution:
          onStart:
            - restore_run_files state ./files
          onExecute:
            - echo "state file contents - "
            - cat ./files/*
            - echo "foo_step_1_steplet_1 --> ${foo_step_1_steplet_1}"
            - echo "bar_step_1_steplet_1 --> ${bar_step_1_steplet_1}"
            - echo "foo_step_1_steplet_2 --> ${foo_step_1_steplet_2}"
            - echo "bar_step_1_steplet_2 --> ${bar_step_1_steplet_2}"
          onComplete:
            - echo "${step_name} Completed"

