pipelines:
  - name: pipelines_hello
    steps:

      - name: step_1
        type: Bash
        execution:
          onExecute:
            - add_run_variables var1="foo"
            - add_run_variables var2="bar"
            - echo "Step 1.."

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - add_run_variables var3="baz"
            - echo "Step 2.."

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo "Step 3.."

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_3
        execution:
          onExecute:
            - echo "Step 4.."

      - name: step_5
        type: Bash
        configuration:
          inputSteps:
            - name: step_4
        execution:
          onExecute:
            - echo "var1 - ${var1}"
            - echo "var2 - ${var2}"
            - echo "var3 - ${var3}"
