pipelines:
  - name: MULTI_NODE_DEMO
    steps:

      - name: MULTI_NODE_DEMO_001
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            - foo: "foo"
            - foo: "bar"
            - foo: "baz"
        execution:
          onStart:
            - set_step_var "steplet_info" "Executed matrix steplet - ${steplet_id} on node id - ${step_node_id}"
          onExecute:
            - echo "Executed matrix steplet - ${steplet_id} on node id - ${step_node_id}"
            - echo "foo value --> $foo"
            - sleep 10

      - name: MULTI_NODE_DEMO_002
        type: Bash
        configuration:
          inputSteps:
            - name: MULTI_NODE_DEMO_001
        execution:
          onExecute:
            - get_step_var "MULTI_NODE_DEMO_001" "steplet_info"
