
resources:
  - name: source_repo
    type: GitRepo
    configuration:
      gitProvider: github
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: master
 
pipelines:     
    - name: pipeline_github_repo_trigger
      steps:
        - name: gitrepo_trigger_step_1
          type: Bash
          execution:
            onExecute:
              - printenv 
